<?php

namespace SnowTricksBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * TrickRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrickRepository extends \Doctrine\ORM\EntityRepository
{
	public function getTricks($page, $nbPerPage)
	{
		$query = $this->createQueryBuilder('t')
		  	->getQuery();

		$query->setFirstResult(($page-1) * $nbPerPage)
			->setMaxResults($nbPerPage);

		return new Paginator($query, true);
	}
}
