snow_tricks_homepage:
    path:     /
    defaults: { _controller: SnowTricksBundle:Trick:index }

snow_tricks_add:
    path:     /add
    defaults: { _controller: SnowTricksBundle:Trick:add }

snow_tricks_details:
    path:     /trick/{slug}
    defaults: { _controller: SnowTricksBundle:Trick:trick }
